# Generated by Django 3.1.5 on 2021-01-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmo', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
